version: "3.5"

services:
  bunny:
    container_name: bunny
    build: ./dist
    restart: always
    networks:
      - web-bunny
    ports:
      - 8080:80

networks:
  web-hive:
    name: web-bunny
